### PR TITLE
fix #82 Nest 8 bug.

### LINKED ISSUE #82: Nest 8 + redis bug
[Nest] 2697522  - 07/09/2021, 12:43:37 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the RedisCoreModule (Symbol(REDIS_MODULE_OPTIONS), ?). Please make sure that the argument ModuleRef at index [1] is available in the RedisCoreModule context.

Potential solutions:
- If ModuleRef is a provider, is it part of the current RedisCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within RedisCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })

### PR DESCRIPTION
**Pull request by GyanendroKh**
This fixes the bug with `ModuleRef` on Nest 8. #82

### CODE REVIEW

**Comment by clayrisser** [comment]
Please accept this pull request as soon as possible.

**Comment by hiagodotme** [comment]
@skunight could you check this for us?

**Comment by issackr** [comment]
+1

**Comment by hiagodotme** [comment]
I solved my problem by updating the repository to `"nestjs-redis": "git+https://github.com/GyanendroKh/nestjs-redis.git#nest8-fix",` in my `package.json`

**Comment by NirosP** [comment]
+1

**Comment by xtrinch** [comment]
+1

**Comment by valkn0t** [comment]
+1

**Comment by baojiawei** [comment]
+1

**Comment by fjcero** [comment]
😬

**Comment by e10101** [comment]
+1

**Comment by SloCompTech** [comment]
@skunight Could you please check & merge this for us ? Thanks

**Comment by fjcero** [comment]
@skunight are you looking for maintainers?

**Comment by hiagodotme** [comment]
👏🏼👏🏼👏🏼👊🏼🚀

**Comment by ChambersChan** [comment]
Wait for publishing.

**Comment by xueqingxiao** [comment]
Wait for publishing.

**Comment by longshao5520** [comment]
Wait for publishing.

**Comment by Gowtham029** [comment]
Wait for publishing.

**Comment by ActiveDev1** [comment]
Wait for publishing.

**Comment by jiahao-si** [comment]
Wait for publishing.

**Pull request merged**
